<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerV2sxaMp\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerV2sxaMp/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerV2sxaMp.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerV2sxaMp\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerV2sxaMp\App_KernelDevDebugContainer([
    'container.build_hash' => 'V2sxaMp',
    'container.build_id' => '6a396daa',
    'container.build_time' => 1684338661,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerV2sxaMp');
